### ISSUE TITLE
Spring Data Elasticsearch 的使用

### ISSUE THREAD

**Issue by coder-yuxing** [coder-yuxing/trainee-parent#16]

**Comment by coder-yuxing** [comment]
## 依赖及配置
### Maven依赖
```xml
 <dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-elasticsearch</artifactId>
    <version>2.4.6</version>
 </dependency>
```

**elasticsearch 版本：7.9.3**

### Spring项目配置
```yaml
spring:
  application:
    name: trainee-search-service
  elasticsearch: 
    rest:
      uris: localhost:9200
      username: elastic
      password:
```

**注：除上述依赖及配置外不需要其他任何额外配置**
#### 日志配置
在开发环境中，若需要查看elasticsearch请求的请求体及响应可在配置文件中引入如下配置：
```yaml
logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            core: DEBUG
```

- [How to enable query logging in Spring-data-elasticsearch](https://stackoverflow.com/questions/30691884/how-to-enable-query-logging-in-spring-data-elasticsearch)

**Comment by coder-yuxing** [comment]
## 使用注解配置Elasticsearch文档元数据与Java对应的映射

### 常用注解介绍
- `@Document`：类级别注解，用于标识该类与elasticsearch中对应索引的映射关系
  - indexName: 指定该类映射的索引名称(索引别名)，**该属性支持使用 SpEL表达式**
  - shards：指定索引的主分片数量
  - replicas：指定索引分片的副本数量
  - createIndex：在索引不存在时是否创建索引，默认为`true`
- `@Id`：字段级别注解，用于标识索引文档的主键
- `@Field`: 字段级别注解，用于指定该字段映射至索引文档时的数据类型、分词器等
  - type：指定文档中的数据类型
  - analyzer：指定字段的分词器

###  代码示例
#### 配置文件配置
```yaml
trainee-search:
  index:
    goods: goods
```

### Java配置
```java

/**
 * 索引文档配置
 *
 * @author yuxing
 * @since 2022/1/14
 */
@Data
@Configuration("searchIndexConfig")
@ConfigurationProperties(prefix = "trainee-search.index")
public class SearchIndexConfig {

    /**
     * 素材索引名称
     */
    private String goods;

}
```

#### Java类与Elasticsearch索引的数据映射代码示例
```java
// #{@searchIndexConfig.getGoods()} 通过 SpEL表达式引入配置文件中配置的索引名称
@Document(indexName = "#{@searchIndexConfig.getGoods()}")
public class EsGoods {

    /**
     * 文档ID
     */
    @Id
    private String id;

    /**
     * 素材名称
     */
    @Field(type = FieldType.Text, analyzer = "ik_max_word")
    private String name;

    /**
     * 素材编码
     */
    @Field(type = FieldType.Keyword)
    private String code;

    /**
     * 素材类型
     */
    private Integer type;
}
```


## Reference
- [Meta Model Object Mapping](https://docs.spring.io/spring-data/elasticsearch/docs/4.1.15/reference/html/#elasticsearch.mapping)
