### ISSUE TITLE
Docker-compose 使用自定义网络并绑定 IP

### ISSUE THREAD

**Issue by coder-yuxing** [coder-yuxing/trainee-parent#19]
### 创建网络
```
docker network create --subnet=172.18.0.0/16 mynetwork
```

### docker-compose.yml中指定自定义网络，并设置IP
示例：
```
version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - '3336:3306'
    volumes:
      - /data/mysql/conf:/etc/mysql/conf.d
      - /data/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      default:
        ipv4_address: 172.18.0.31

networks:
  default:
    external:
      name: mynetwork
```
